---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 11.10.4


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[mysql_role::default]
    attributes:
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
